### ISSUE TITLE
OSM Teams Feature Requests (YM Phase III) Master List

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#282]
Starting this list here, can be moved into a Project, but starting it here: @kamicut 

### 1. General UI/UX Improvements: 

**Team Detail Page**
- [x] #290
- [x] #291
- [x] #292

**User Detail Popup**
- [x] #293
- [x] #294

**Organization Page**
- [x] List of teams in an organization instead of (or above) list of users.  (https://github.com/developmentseed/osm-teams/issues/268)

### 2. Badge Improvements

- [x] #295
- [x] #296

### 3. OSM Username Lookups
- [ ] Enable adding an OSM user by OSM username. https://github.com/developmentseed/osm-teams/issues/97

**Comment by batpad** [comment]
Adding tickets here that should ideally be part of this phase, in order of priority:

 - [ ] Fix redirect after login: https://github.com/developmentseed/osm-teams/issues/318
 - [ ] Make table on Team Detail page searchable + sortable: https://github.com/developmentseed/osm-teams/issues/319
 - [ ] Add Join Button for Teams: https://github.com/developmentseed/osm-teams/issues/320
 - [ ] Export CSV of Teams: https://github.com/developmentseed/osm-teams/issues/301

**Comment by LanesGood** [comment]
The release of version 2.2 closes this ticket and marks the full delivery of all discussed features.

The additional open tickets have all been discussed as potential later enhancements.
