### ISSUE TITLE
Production deployment / Moving to Vercel Checklist

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#343]
Here's the checklists of things we need to do to move production to a Vercel deployment

- [x] merge develop into main branch
- [x] make an RDS for production and move the data there
- [x] move v1 to maintenance
- [x] point the vercel production deployment to the new database
- [x] Create an OAuth client for the production vercel deployment
- [x] Change env vars in Vercel to separate dev and prod oauth clients
- [x] move the A record for mapping.team to the new production URL

**Comment by batpad** [comment]
This is done! 🎉 Great work all!
